### ISSUE TITLE
User cards won't show up in some cases

### ISSUE THREAD

**Issue by justcool393** [themotte/rDrama#612] opened 2023-07-08 05:16 UTC
steps to repro:

1. make a comment
2. click on your username in the replied comment
3. observe the user card doesn't show up

**Comment by TLSM** [comment] 2023-07-08 05:25
I recall we had this issue on upstream. Think the issue is the popup user card is from Bootstrap, which only attaches listeners on document ready and thus does not on elements added to the DOM late. This is mitigated elsewhere through explicit calls to `bs_trigger(element)` on the newly added element. Probably just need to do the same in `comments_v.js:post_comment`. Right now we seem to be doing it on the comment submission form, whereas this was previously fixed on upstream by calling bs_trigger on the element with id `'replies-of-' + fullname`

**Closed as completed** 2023-07-09 18:38 UTC
Labels: bug, P3 desired
